package applesign

import (
	"context"
	"github.com/pkg6/go-requests"
	"net/url"
)

// RevokeAccessTokenRequest is based off https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens
type RevokeAccessTokenRequest struct {
	// ClientID is the "Services ID" value that you get when navigating to your "sign in with Apple"-enabled service ID
	ClientID string
	// ClientSecret is secret generated as a JSON Web Token that uses the secret key generated by the WWDR portal.
	// It can also be generated using the GenerateClientSecret function provided in this package
	ClientSecret string
	// AccessToken is the auth token given during a previous validation
	AccessToken string
}

func RevokeAccessToken(ctx context.Context, reqBody RevokeAccessTokenRequest) error {
	data := url.Values{}
	data.Set("client_id", reqBody.ClientID)
	data.Set("client_secret", reqBody.ClientSecret)
	data.Set("token", reqBody.AccessToken)
	data.Set("token_type_hint", "access_token")
	resp, err := requests.New().AsForm().Post(ctx, RevokeURL, data)
	if err != nil || resp.IsError() {
		return err
	}
	return nil
}
