package applesign

import (
	"context"
	"github.com/pkg6/go-requests"
	"net/url"
)

// ValidationRefreshRequest is based off of https://developer.apple.com/documentation/signinwithapplerestapi/generate_and_validate_tokens
type ValidationRefreshRequest struct {
	// ClientID is the "Services ID" value that you get when navigating to your "sign in with Apple"-enabled service ID
	ClientID string

	// ClientSecret is secret generated as a JSON Web Token that uses the secret key generated by the WWDR portal.
	// It can also be generated using the GenerateClientSecret function provided in this package
	ClientSecret string

	// RefreshToken is the refresh token given during a previous validation
	RefreshToken string
}

func VerifyRefreshToken(ctx context.Context, req ValidationRefreshRequest) (*ValidationTokenResponse, error) {
	resp := new(ValidationTokenResponse)
	data := url.Values{}
	data.Set("client_id", req.ClientID)
	data.Set("client_secret", req.ClientSecret)
	data.Set("refresh_token", req.RefreshToken)
	data.Set("grant_type", "refresh_token")
	_, err := requests.New().AsForm().PostD(ctx, ValidationURL, data, &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
